version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lucifers-0666"
    labels:
      - "dependencies"
      - "dart"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "disabled"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first"
    open-pull-requests-limit: 5
    reviewers:
      - "lucifers-0666"
    labels:
      - "ci/cd"
      - "automation"
    commit-message:
      prefix: "ci"
    pull-request-branch-name:
      separator: "/"
